services:
  har_server:
    build:
      context: ./server
    ports:
      - 1394:1394
    volumes:
      - api-volume:/app/api
    depends_on:
      - har_compiler
  har_compiler:
    build:
      context: ./harToMocks
    volumes:
      - api-volume:/app/api
      - ./harToMocks/currentHar:/app/currentHar

networks:
  default:
    name: nop-local-network
    external: true

volumes:
  api-volume:

