services:
  mock_server:
    build:
      context: ./server
    ports:
      - 777:777
    volumes:
      - api-volume:/app/api
    depends_on:
      - har_to_mocks_compiler
  har_to_mocks_compiler:
    build:
      context: ./harToMocks
    # ports:
    #   - 777:777
    volumes:
      - api-volume:/app/api
      - ./harToMocks/currentHar:/app/currentHar

networks:
  default:
    name: nop-local-network
    external: true

volumes:
  api-volume:

